const jobs = [
  {
    id: 1,
    jobTitle: "Online English Tutor",
    company: "PlanetSpark",
    jobType: "Part-time",
    location: "Madhya Pradesh, Mumbai, Delhi",
    startDate: "Immediately",
    experience: "1-5 years",
    stipend: "3,00,000 LPA",
    date: "06-05-2024",
    jobDescription: "About the jobKey responsibilities:1. Conduct demo classes as per the PlanetSpark content and methodology2. Ensure an amazing demo experience for the child and parent3. Conduct regular classes (post enrolment) using an in-house curriculum4. Ensure timely feedback to the child5. Adhere to the schedule for the demo as well as regular classesWhat are the behavioral attributes that we are looking for?1. Excellent teaching skills2. Excellent attention to detail, and strong communication skills - both written and verbal3. Ability to build strong relationships with the child/learner and make the class fun-based learning4. Tech-savvyEligibility criteria:1. Excellent verbal and written communication2. Willing to work 6 days a week (should be available on Saturdays & Sundays)3. Willing to invest 3-4 teaching hours every day4. At least 1 year of English teaching experience5. Should have good Wi-Fi and a laptop with a webcamSkill(s) requiredAmerican EnglishBritish EnglishEnglish Proficiency (Spoken)English Proficiency (Written)",
    ApplyBy: "05-06-2024",
  },
  {
    id: 2,
    jobTitle: "Customer Experience Executive",
    company: "Guby Rogers",
    jobType: "Full-Time",
    location: "Gurgaon",
    startDate: "Immediately",
    experience: "0-3 years",
    stipend: "4,00,000 LPA",
    date: "06-05-2024",
    jobDescription: "About the jobKey responsibilities:1. Interact with customers via phone, email, and in-person to address their queries and concerns promptly and professionally2. Provide accurate and timely information regarding products, services, and company policies3. Troubleshoot and resolve customer issues efficiently to ensure a positive customer experience4. Collaborate with internal teams to escalate and resolve complex customer problems5. Maintain detailed records of customer interactions and transactions6. Identify and recommend process improvements to enhance customer satisfactionRequirements:1. Experience in a fast-paced customer service and hospitality role2. Strong communication skills with proficiency in typing and speaking efficiently3. Excel at managing the resolution process, ensuring that communication remains clear and concise throughout4. Solution-seeking and problem-solving is your passion5. You thrive on creating positive experiences with empathy",
    ApplyBy: "05-06-2024",
  },
  {
    id: 3,
    jobTitle: "Video Editing",
    company: "The Future University",
    jobType: "Part-Time",
    location: "Chandigarh",
    startDate: "Immediately",
    experience: "0-2 years",
    stipend: "3-6LPA",
    date: "09-05-2024",
    jobDescription: "About the job As a Video Editor at The Future University, you will have the exciting opportunity to showcase your skills in video editing, Adobe Premiere Pro, Final Cut Pro, and video production. Your creativity and technical expertise will play a crucial role in helping us create engaging and high-quality video content for our university. Key Responsibilities: 1. Edit and produce engaging videos for various university departments and projects. 2. Collaborate with the marketing team to develop video concepts and storyboards. 3. Manage video assets and ensure all content is organized and easily accessible. 4. Stay up-to-date on industry trends and best practices in video editing and production. 5. Work closely with the creative team to ensure brand consistency across all video projects. 6. Provide feedback and recommendations for improving video quality and production processes. 7. Meet tight deadlines and deliver high-quality video content that exceeds expectations. If you are a passionate and talented video editor looking to make a real impact in the world of higher education, we want to hear from you. Join our team at The Future University and help us shape the future of education through the power of video storytelling. Skill(s) required Adobe Premiere Pro Final Cut Pro Video Editing Video Making",
    ApplyBy: "08-06-2024",
  },
  {
    id: 4,
    jobTitle: "Customer Sales Assoc.",
    company: "Neelam Saini",
    jobType: "Full-Time/Part-Time",
    location: "Delhi",
    startDate: "Immediately",
    experience: "0-2 years",
    stipend: "3,00,000-4,20,000 LPA",
    date: "23-04-2024",
    jobDescription: "About the job Key responsibilities: 1. Work on understanding customers' requirements and solving their queries. 2. Handle architects/interior designers or consultants. 3. Help build relationships as well as develop a new client base to generate more revenue. 4. Handle in Audio Video/ Public Address/visual display fields with OEM, Distributor, or SI. 4. Manage B2B and B2C sales. 5. Work on problem-solving. Skill(s) required: English Proficiency (Spoken), Marketing, Problem Solving, Sales, Salesforce, Sales pitch", 
    ApplyBy: "26-05-2024",
  },
  {
    id: 5,
    jobTitle: "Associate Accountant",
    company: "Avega Business Solutions Pvt. Ltd.",
    jobType: "Full-Time",
    location: "Bangalore",
    startDate: "Immediately",
    experience: "0-1 years",
    stipend: "2.4LPA",
    date: "09-05-2024",
    jobDescription: "About the job Are you a detail-oriented individual with a passion for numbers and financial analysis? Avega Business Solutions Private Limited is seeking a dynamic associate accountant to join our team. As an associate accountant, you will play a crucial role in managing financial records, preparing financial statements, and ensuring compliance with accounting standards. Key responsibilities: 1. Perform day-to-day accounting tasks using Tally software 2. Prepare and maintain accurate financial records and reports 3. Assist in budgeting and forecasting activities 4. Reconcile bank statements and ensure all transactions are recorded correctly 5. Assist in the preparation of tax returns and other financial documents 6. Communicate effectively with clients and stakeholders regarding financial matters 7. Collaborate with team members to improve accounting processes and procedures If you have strong proficiency in MS Office, Tally, and MS Excel, along with excellent English communication skills, we want to hear from you! Join us at Avega Business Solutions Private Limited and take your accounting career to the next level. Apply now! Skill(s) required Accounting English Proficiency (Spoken) English Proficiency (Written) MS-Excel MS-Office Tally",
    ApplyBy: "08-06-2024",
  },
  {
    id: 6,
    jobTitle: "HR Recruiter",
    company: "IntraAstro",
    jobType: "Full-Time/Part-Time",
    location: "Noida",
    startDate: "Immediately",
    experience: "0-1 years",
    stipend: "2-3 LPA",
    date: "09-05-2024",
    jobDescription: "About the job Are you a passionate HR Recruiter looking to join a dynamic and innovative team? InstaAstro is seeking a highly skilled professional to join our growing company. As a key member of our team, you will be responsible for sourcing, screening, and interviewing potential candidates to fill various positions within the company. Your strong recruitment skills, effective communication, and proficiency in MS-Excel will be instrumental in ensuring the success of our recruitment efforts. Key Responsibilities: 1. Collaborate with hiring managers to identify recruitment needs and develop effective recruitment strategies. 2. Source and attract top talent through various channels, including job boards, social media, and networking events. 3. Screen resumes and conduct interviews to assess candidates' qualifications and fit for the role. 4. Manage the candidate experience from application to onboarding, ensuring a smooth and positive recruitment process. 5. Utilize MS-Excel to track and analyze recruitment metrics, providing insights to improve recruitment strategies. 6. Build and maintain strong relationships with candidates and external partners to enhance the recruitment process. 7. Stay up-to-date on industry trends and best practices to continuously improve recruitment processes and techniques. If you are a motivated and results-driven individual with a passion for recruitment, we want to hear from you! Join us at InstaAstro and be part of a team that is dedicated to making a difference in the world of HR. Apply now and take your career to new heights! Skill(s) required Effective Communication MS-Excel Recruitment",
    ApplyBy: "08-06-2024",
  },
  {
    id: 7,
    jobTitle: "Full Stack Developer",
    company: "Binary Numbers",
    jobType: "Full-Time",
    location: "Remote",
    startDate: "Anytime",
    experience: "0-5 years",
    stipend: "6-10LPA",
    date: "09-05-2024",  
    jobDescription: "About the job Key responsibilities: 1. Building reliable, responsive, and performant front-end web applications 2. Collaborate with technical leaders, business analysts, managers, architects, and other software developers, along with internal customers, to understand and develop solutions 3.Develop the required specialized pieces/ end-to-end solutions for multi-layered applications on a variety of technology stacks 4. Troubleshoot and debug complex software issues; identify and implement solutions 5. Create detailed functional specifications, and acceptance criteria according to requirements, and provide realistic work estimates 6. Research and implement new or unfamiliar technologies with limited guidance 7. Support adherence to high-quality coding standards and adhere to best practices, security guidelines, and automated regression testing 8. Contribute to software architecture and design Skill(s) required JavaScript MySQL Node.js ReactJS REST API Vue Js",
    ApplyBy: "08-06-2024",
  },
  {
    id: 8,
    jobTitle: "Wordpress Developer",
    company: "Confluencer",
    jobType: "Full-Time",
    location: "Bangalore",
    startDate: "Immediately",
    experience: "1-3 years",
    stipend: "3-5 LPA",
    date: "08-05-2024",
    jobDescription: "About the job Key responsibilities: 1. Develop custom WordPress themes, as well as Shopify themes, based on client requirements and design specifications 2. Customize and extend existing WordPress and Shopify functionality using HTML, CSS, JavaScript, PHP, Liquid, and other relevant technologies 3. Collaborate with designers to implement responsive and visually appealing website designs that enhance user experience and brand identity 4. Optimize WordPress and Shopify websites for speed, performance, and search engine visibility 5. Integrate third-party APIs and services, such as payment gateways, shipping providers, and CRM systems, to enhance website functionality and e-commerce capabilities 6. Conduct thorough testing and debugging of websites to ensure cross-browser compatibility, accessibility, and responsiveness 7. Stay updated with the latest WordPress and Shopify trends, techniques, and best practices, and leverage this knowledge to propose innovative solutions and optimizations 8. Provide technical support and troubleshooting assistance to clients and internal stakeholders as needed Candidate should be familiar with WordPress. Skill(s) required HTML JavaScript WordPress",
    ApplyBy: "07-06--2024",
  },
  {
    id: 9,
    jobTitle: "Associate Java Developer",
    company: "Bharat Hyundai",
    jobType: "Full=Time",
    location: "Hyderabad",
    startDate: "August",
    experience: "0-3 years",
    stipend: "5-8LPA",
    date: "06-04-2024",
    jobDescription: "About the job Key responsibilities: Key Responsibilities for Associate Java Developer Role: 1. Develop and maintain Java-based applications. 2. Collaborate with cross-functional teams to design and implement software solutions. 3. Write clean, efficient, and well-documented code. 4. Conduct unit testing and debugging to ensure software quality. 5. Participate in code reviews and provide constructive feedback to team members. Skill(s) required .NET 3ds Max Hibernate (Java) J2EE Java JSP MySQL Spring MVC",
    ApplyBy: "26-05-2024",
  },
  {
    id: 10,
    jobTitle: "PHP Developer",
    company: "Orbiqe Technologies Pvt. Ltd.",
    jobType: "Full-Time",
    location: "Meerut",
    startDate: "Next Month",
    experience: "1+ years",
    stipend: "4LPA",
    date: "15-05-2024",
    jobDescription: "About the job Best chance to add Govt project on your Resume. Role : PHP Web Developer Experience : 1+ year Location: Meerut Cantt. Notice Period : Immediate/15 Days Contract Duration 3 Month Selection Process - Three Rounds(Technical Round + Management+ Technical) Key responsibilities: 1. Do system analyses, coding and testing of the application 2. Ensure team handling and team coordination 3. Do client communication when it's necessary 4. Report to client with status of the work on daily basis 5. Do testing of the system 6. Handle team when it's needed and report to management Skills required: 1. Minimum 1+ years of continuous experience in working on PHP framework like Code Ingiter, Laravel or combination of these 2. Experience must be working on front-end/backend development assignments 3. Education: B.E/B. Tech/M.Tech or MCA from a recognized university",
    ApplyBy: "26-05-2024",
  },
  {
    id: 11,
    jobTitle: "Senior AngularJs Developer",
    company: "Bharat Hyundai",
    jobType: "Full-Time",
    location: "Hyderabad",
    startDate: "After 15-06-2024",
    experience: "2+ years",
    stipend: "10LPA",
    date: "03-06-2024",
    jobDescription: "About the job Key responsibilities: 1.1. Strong experience with Angular latest versions (8 & above) 2. Strong knowledge of HTML, CSS3, Mobile responsiveness and jQuery 3. Strong JavaScript concepts 4. Experience of integrating Rest APIs 5. Proficient understanding code versioning tools such as GIT Repository 6. Good knowledge with browser caching, working with cookies and java scripts for faster website loads. 7. Clean coding style with clear separation of UI and functionality. 8. Good to have experience in Karma, Jasmine or any unit testing framework 9. Should be passionate about programming and coding skills Skill(s) required Angular 2.0 Angular 7.0 AngularJS CSS HTML JavaScript Node.js",
    ApplyBy: "06-08-2024",
  },
  {
    id: 12,
    jobTitle: "Web Developer",
    company: "Infosys",
    jobType: "Part-Time",
    location: "Remote",
    startDate: "20-07-2024",
    experience: "No experiene required",
    stipend: "4-7LPA",
    date: "23-03-2024",
    jobDescription: "About the job We are looking for a web developer to manage our website and develop a new website for our clients as per the requirement. You will be responsible for managing and developing the website according to the project requirements This will also include updating crawlers and other SEO requirements as and when required by the SEO team Key responsibilities: 1. Doing website and software application designing, building, or maintaining. 2. Using scripting or authoring languages, management tools, content creation tools, applications, and digital media. 3. Conferring with teams to resolve conflicts, prioritize needs, develop content criteria, or choose solutions 4. Directing or performing Website updates as required 5. Developing or validating test routines and schedules to ensure that test cases mimic external interfaces and address all browser and device types 6. Editing, writing, or designing Website content, and directing team members who produce content 7. Maintaining an understanding of the latest Web applications and programming practices through education, study, and participation in conferences, workshops, and groups 8. Backing up files from websites to local directories for recovery 9. Identifying problems uncovered by customer feedback and testing and correcting or referring problems to appropriate personnel for correction 10. Evaluating code to ensure it meets industry standards, is valid, is properly structured, and is compatible with browsers, devices, or operating systems 11. Determining user needs by analyzing technical requirements Requirements: 1. Minimum 1+ year of web development experience 2. Ability to thrive in a fast-paced environment 3. Working knowledge of web applications, programming languages, and web services, such as APIs, CSS, CSS3, cross-browser compatibility, HTML, HTML5, jQuery, PHP, Laravel, HTML, JavaScript, Bootstrap 4. Proficiency with content management systems, including WordPress and Drupal 5. Dedication to innovative, sophisticated designs and collaborative problem-solving 6. Working experience in Windows and Linux environments 7. Knowledge of app development is a benefit 8. Experience implementing and using modern web development workflows and operations using a variety of tools including GitHub Skill(s) required HTML LARAVEL PHP WordPress",
    ApplyBy: "26-05-2024",
  },
  {
    id: 13,
    jobTitle: "Backend Developer",
    company: "INI8 Labs Pvt. Ltd.",
    jobType: "Full-Time",
    location: "Chennai",
    startDate: "Immediately",
    experience: "3+ years",
    stipend: "5-15LPA",
    date: "23-03-2024",
    jobDescription: "About the job We are looking for an experienced Python/Go developer to join our dynamic team. The desired candidate possesses a strong commitment to crafting clean, efficient, and maintainable code. The required experience is 3- 5 years. Key responsibilities: 1. API Development - Create, design, and manage APIs, preferably in Python Or Go Language 2. Expertise in comprehending and implementing gRPC Communication protocols 3. WebSocket Proficiency - Exhibit a strong understanding of web sockets and how they enable real-time communication 4. Efficiently work with SQL Databases like PostgreSQL, and NoSQL databases such as MongoDB, to manage data storage and retrieval 5. Use Caching Techniques and tools like Redis to enhance system performance 6. Set up and Understand Pub/Sub architectures to ease streamlined event-driven performance 7. Demonstrate expertise in using Docker and Container Technologies for effective deployment and scaling 8. Apply Coding Principles, Including SOLID to create code that is maintainable, extendable, and readable Qualifications: 1. Bachelor s or master s degree in computer science, engineering, or a related field 2. 3 -5 years of proven experience in software development with a strong emphasis on Python or Go 3. Understanding of software architecture and design patterns 4. Familiarity with Go is an added advantage 5. Excellent problem-solving skills and the ability to work collaboratively in a team 6. Strong communication skills with a capacity to convey technical concepts to any of the stakeholders 7. Excellent verbal and written communication skills Skill(s) required Golang Java MongoDB MySQL Python REST API",
    ApplyBy: "26-03-2024",
  },
  {
    id: 14,
    jobTitle: "Robotics Instructor",
    company: "Rancho Labs",
    jobType: "Full-Time",
    location: "Chennai",
    startDate: "Immediately",
    experience: "2 years",
    stipend: "6LPA",
    date: "12-04-2024",
    jobDescription: "About the job Key responsibilities: 1. Teach coding and robotics concepts to K-12 students using Arduino and Microbit platforms 2. Develop and update curriculum, lesson plans, and educational materials to align with learning objectives and standards 3. Instruct students in C++ and python programming fundamentals and applications related to robotics and embedded systems 4. Provide hands-on coding exercises, projects, and challenges to enhance students' programming skills and problem-solving abilities 5. Conduct R&D activities to explore new technologies, tools, and methodologies in robotics education 6. Collaborate with the R&D team to innovate and improve educational content, hardware/software integration, and instructional approaches 7. Create comprehensive documentation, tutorials, and guides for Arduino, Microbit, and C++ programming to support students, educators, and parents 8. Develop digital and printed resources, including manuals, workbooks, and online content, to facilitate self-paced learning and practices 9. Collaborate with fellow instructors and curriculum developers to coordinate program delivery, assessment, and continuous improvement Skill(s) required Arduino C++ Programming Python",
    ApplyBy: "26-04-2024",
  },
  {
    id: 15,
    jobTitle: "Java Developer",
    company: "Saregama India Ltd.",
    jobType: "Full-Time/Part-Time",
    location: "Hybrid",
    startDate: "Immediately",
    experience: "1-5 year",
    stipend: "7-10LPA",
    date: "23-04-2024",
    jobDescription: "About the job Key responsibilities include: 1. Write clean, scalable, and efficient code using Java programming language 2. Develop back-end components to improve responsiveness and overall performance 3. Implement and maintain Java applications that are high-volume and low-latency 4. Develop and conduct unit tests to ensure the application meets its design and behavioral specifications 5. Make existing software systems more efficient by analyzing and identifying areas for modification and improvement Requirements: 1. Proficient in coding in Java, with a solid understanding of underpinning techniques of object-oriented programming, programming concepts, development of distributed systems, and best practices (e.g. style guidelines, testability, efficiency, observability, scalability, security) 2. Experience in: Amazon Web Service 3. Experience with Kafka or proficiency with other Streaming or Queue-based technologies Skill(s) required Amazon Web Services (AWS) Java",
    ApplyBy: "26-05-2024",
  },
  {
    id: 16,
    jobTitle: "Senior ReactJS Developer",
    company: "Bharat Hyundai",
    jobType: "Full-Time/Part-Time",
    location: "Work From Home",
    startDate: "After 15-06-2024",
    experience: "3+ years",
    stipend: "9LPA",
    date: "23-04-2024",
    jobDescription: "About the job Key responsibilities: 1. Develop responsive user interface components using React.js 2. Collaborate with the design team to translate UI/UX designs into code 3. Optimize applications for maximum performance across a wide range of web-capable devices and browsers 4. Work closely with other team members and stakeholders to gather and understand requirements 5. Participate in code reviews and offer constructive feedback 6. Troubleshoot, debug and resolve software defects and issues 7. Stay abreast of emerging technologies and industry trends to ensure continuous improvement of our applications Skill(s) required HTML&CSS React ReactJS Redux REST API",
    ApplyBy: "06-05-2024",
  },
];
export default jobs;