const jobs = [
  {
    id: 1,
    jobTitle: "Online English Tutor",
    company: "PlanetSpark",
    jobType: "Part-time",
    location: "Madhya Pradesh, Mumbai, Delhi",
    startDate: "Immediately",
    experience: "1-5 years",
    stipend: "3,00,000 LPA",
    date: "06-05-2024",
    jobDescription: "About the jobKey responsibilities:1. Conduct demo classes as per the PlanetSpark content and methodology2. Ensure an amazing demo experience for the child and parent3. Conduct regular classes (post enrolment) using an in-house curriculum4. Ensure timely feedback to the child5. Adhere to the schedule for the demo as well as regular classesWhat are the behavioral attributes that we are looking for?1. Excellent teaching skills2. Excellent attention to detail, and strong communication skills - both written and verbal3. Ability to build strong relationships with the child/learner and make the class fun-based learning4. Tech-savvyEligibility criteria:1. Excellent verbal and written communication2. Willing to work 6 days a week (should be available on Saturdays & Sundays)3. Willing to invest 3-4 teaching hours every day4. At least 1 year of English teaching experience5. Should have good Wi-Fi and a laptop with a webcamSkill(s) requiredAmerican EnglishBritish EnglishEnglish Proficiency (Spoken)English Proficiency (Written)",
    ApplyBy: "05-06-2024",
  },
  {
    id: 2,
    jobTitle: "Customer Experience Executive",
    company: "Guby Rogers",
    jobType: "Full-Time",
    location: "Gurgaon",
    startDate: "Immediately",
    experience: "0-3 years",
    stipend: "4,00,000 LPA",
    date: "06-05-2024",
    jobDescription: "About the jobKey responsibilities:1. Interact with customers via phone, email, and in-person to address their queries and concerns promptly and professionally2. Provide accurate and timely information regarding products, services, and company policies3. Troubleshoot and resolve customer issues efficiently to ensure a positive customer experience4. Collaborate with internal teams to escalate and resolve complex customer problems5. Maintain detailed records of customer interactions and transactions6. Identify and recommend process improvements to enhance customer satisfactionRequirements:1. Experience in a fast-paced customer service and hospitality role2. Strong communication skills with proficiency in typing and speaking efficiently3. Excel at managing the resolution process, ensuring that communication remains clear and concise throughout4. Solution-seeking and problem-solving is your passion5. You thrive on creating positive experiences with empathy",
    ApplyBy: "05-06-2024",
  },
  {
    id: 3,
    jobTitle: "Video Editing",
    company: "The Future University",
    jobType: "Part-Time",
    location: "Chandigarh",
    startDate: "Immediately",
    experience: "0-2 years",
    stipend: "3-6LPA",
    date: "09-05-2024",
    jobDescription: "About the job As a Video Editor at The Future University, you will have the exciting opportunity to showcase your skills in video editing, Adobe Premiere Pro, Final Cut Pro, and video production. Your creativity and technical expertise will play a crucial role in helping us create engaging and high-quality video content for our university. Key Responsibilities: 1. Edit and produce engaging videos for various university departments and projects. 2. Collaborate with the marketing team to develop video concepts and storyboards. 3. Manage video assets and ensure all content is organized and easily accessible. 4. Stay up-to-date on industry trends and best practices in video editing and production. 5. Work closely with the creative team to ensure brand consistency across all video projects. 6. Provide feedback and recommendations for improving video quality and production processes. 7. Meet tight deadlines and deliver high-quality video content that exceeds expectations. If you are a passionate and talented video editor looking to make a real impact in the world of higher education, we want to hear from you. Join our team at The Future University and help us shape the future of education through the power of video storytelling. Skill(s) required Adobe Premiere Pro Final Cut Pro Video Editing Video Making",
    ApplyBy: "08-06-2024",
  },
  {
    id: 4,
    jobTitle: "Customer Sales Assoc.",
    company: "Neelam Saini",
    jobType: "Full-Time/Part-Time",
    location: "Delhi",
    startDate: "Immediately",
    experience: "0-2 years",
    stipend: "3,00,000-4,20,000 LPA",
    date: "23-04-2024",
    jobDescription: "About the job Key responsibilities: 1. Work on understanding customers' requirements and solving their queries. 2. Handle architects/interior designers or consultants. 3. Help build relationships as well as develop a new client base to generate more revenue. 4. Handle in Audio Video/ Public Address/visual display fields with OEM, Distributor, or SI. 4. Manage B2B and B2C sales. 5. Work on problem-solving. Skill(s) required: English Proficiency (Spoken), Marketing, Problem Solving, Sales, Salesforce, Sales pitch", 
    ApplyBy: "26-05-2024",
  },
  {
    id: 5,
    jobTitle: "Associate Accountant",
    company: "Avega Business Solutions Pvt. Ltd.",
    jobType: "Full-Time",
    location: "Bangalore",
    startDate: "Immediately",
    experience: "0-1 years",
    stipend: "2.4LPA",
    date: "09-05-2024",
    jobDescription: "About the job Are you a detail-oriented individual with a passion for numbers and financial analysis? Avega Business Solutions Private Limited is seeking a dynamic associate accountant to join our team. As an associate accountant, you will play a crucial role in managing financial records, preparing financial statements, and ensuring compliance with accounting standards. Key responsibilities: 1. Perform day-to-day accounting tasks using Tally software 2. Prepare and maintain accurate financial records and reports 3. Assist in budgeting and forecasting activities 4. Reconcile bank statements and ensure all transactions are recorded correctly 5. Assist in the preparation of tax returns and other financial documents 6. Communicate effectively with clients and stakeholders regarding financial matters 7. Collaborate with team members to improve accounting processes and procedures If you have strong proficiency in MS Office, Tally, and MS Excel, along with excellent English communication skills, we want to hear from you! Join us at Avega Business Solutions Private Limited and take your accounting career to the next level. Apply now! Skill(s) required Accounting English Proficiency (Spoken) English Proficiency (Written) MS-Excel MS-Office Tally",
    ApplyBy: "08-06-2024",
  },
  {
    id: 6,
    jobTitle: "HR Recruiter",
    company: "IntraAstro",
    jobType: "Full-Time/Part-Time",
    location: "Noida",
    startDate: "Immediately",
    experience: "0-1 years",
    stipend: "2-3 LPA",
    date: "09-05-2024",
    jobDescription: "About the job Are you a passionate HR Recruiter looking to join a dynamic and innovative team? InstaAstro is seeking a highly skilled professional to join our growing company. As a key member of our team, you will be responsible for sourcing, screening, and interviewing potential candidates to fill various positions within the company. Your strong recruitment skills, effective communication, and proficiency in MS-Excel will be instrumental in ensuring the success of our recruitment efforts. Key Responsibilities: 1. Collaborate with hiring managers to identify recruitment needs and develop effective recruitment strategies. 2. Source and attract top talent through various channels, including job boards, social media, and networking events. 3. Screen resumes and conduct interviews to assess candidates' qualifications and fit for the role. 4. Manage the candidate experience from application to onboarding, ensuring a smooth and positive recruitment process. 5. Utilize MS-Excel to track and analyze recruitment metrics, providing insights to improve recruitment strategies. 6. Build and maintain strong relationships with candidates and external partners to enhance the recruitment process. 7. Stay up-to-date on industry trends and best practices to continuously improve recruitment processes and techniques. If you are a motivated and results-driven individual with a passion for recruitment, we want to hear from you! Join us at InstaAstro and be part of a team that is dedicated to making a difference in the world of HR. Apply now and take your career to new heights! Skill(s) required Effective Communication MS-Excel Recruitment",
    ApplyBy: "08-06-2024",
  },
  {
    id: 7,
    jobTitle: "Associate Java Developer",
    company: "Bharat Hyundai",
    jobType: "Full=Time",
    location: "Hyderabad",
    startDate: "August",
    experience: "0-3 years",
    stipend: "5-8LPA",
    date: "06-04-2024",
    jobDescription: "About the job Key responsibilities: Key Responsibilities for Associate Java Developer Role: 1. Develop and maintain Java-based applications. 2. Collaborate with cross-functional teams to design and implement software solutions. 3. Write clean, efficient, and well-documented code. 4. Conduct unit testing and debugging to ensure software quality. 5. Participate in code reviews and provide constructive feedback to team members. Skill(s) required .NET 3ds Max Hibernate (Java) J2EE Java JSP MySQL Spring MVC",
    ApplyBy: "26-05-2024",
  },
  {
    id: 8,
    jobTitle: "Backend Developer",
    company: "INI8 Labs Pvt. Ltd.",
    jobType: "Full-Time",
    location: "Chennai",
    startDate: "Immediately",
    experience: "3+ years",
    stipend: "5-15LPA",
    date: "23-03-2024",
    jobDescription: "About the job We are looking for an experienced Python/Go developer to join our dynamic team. The desired candidate possesses a strong commitment to crafting clean, efficient, and maintainable code. The required experience is 3- 5 years. Key responsibilities: 1. API Development - Create, design, and manage APIs, preferably in Python Or Go Language 2. Expertise in comprehending and implementing gRPC Communication protocols 3. WebSocket Proficiency - Exhibit a strong understanding of web sockets and how they enable real-time communication 4. Efficiently work with SQL Databases like PostgreSQL, and NoSQL databases such as MongoDB, to manage data storage and retrieval 5. Use Caching Techniques and tools like Redis to enhance system performance 6. Set up and Understand Pub/Sub architectures to ease streamlined event-driven performance 7. Demonstrate expertise in using Docker and Container Technologies for effective deployment and scaling 8. Apply Coding Principles, Including SOLID to create code that is maintainable, extendable, and readable Qualifications: 1. Bachelor s or master s degree in computer science, engineering, or a related field 2. 3 -5 years of proven experience in software development with a strong emphasis on Python or Go 3. Understanding of software architecture and design patterns 4. Familiarity with Go is an added advantage 5. Excellent problem-solving skills and the ability to work collaboratively in a team 6. Strong communication skills with a capacity to convey technical concepts to any of the stakeholders 7. Excellent verbal and written communication skills Skill(s) required Golang Java MongoDB MySQL Python REST API",
    ApplyBy: "26-03-2024",
  },
];
export default jobs;